version: '3.8'

services:
  # Service untuk Nginx
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - my_network
    restart: always
    configs:
      - source: example_config
        target: /etc/nginx/example_config.txt

  # Service untuk PostgreSQL
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network
    restart: always
    configs:
      - source: example_config
        target: /etc/postgresql/example_config.txt

  # Service untuk pgAdmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - my_network
    restart: always
    configs:
      - source: example_config
        target: /etc/pgadmin/example_config.txt

  # Service untuk MySQL
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_network
    restart: always
    ports:
      - "3306:3306"

  # Service untuk WordPress
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: userpassword
    ports:
      - "8080:80"
    networks:
      - my_network
    restart: always

volumes:
  postgres_data:
  mysql_data:
  pgadmin_data:

networks:
  my_network:
    driver: bridge

configs:
  example_config:
    file: ./example_config.txt